application:
  # dev开发环境 test测试环境 prod线上环境
  mode: dev
  # 服务器ip，默认使用 0.0.0.0
  host: 0.0.0.0
  # 服务名称
  name: oms
  # 端口号
  port: 8000 # 服务端口号
  readtimeout: 1
  writertimeout: 2
  # 数据权限功能开关
  enabledp: false
databases:
  mia_mirror:
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: houduan_zhangli:Zl123@mia.com@tcp(10.5.96.80:3306)/mia_mirror?charset=utf8mb4&parseTime=True&loc=Local
cache:
  redis:
    addr: 127.0.0.1:6379
    password:
    db: 2
locker:
  redis:
log:
  level: debug
  path: logs/oms.log
